### ISSUE TITLE
[version_0.5]Clear button does not display as soon as you enter the home/office edit page

### ISSUE THREAD

**Issue by Joeyd321** [Telenav-Search/search-android-demo-app#13]
step:
1. Enter home/ office edit page
2. Check text box 
expect:
The clear button will display as soon as you enter the edit page 
actual:
The clear button display after click delete button in keyboard

**Comment by arambaghdasintellias** [comment]
Clear button shows in case of user input text. What is the purpose to show clear when text is empty? What is the expected behavior in case of clicking on clear button ?

**Comment by Joeyd321** [comment]
> Clear button shows in case of user input text. What is the purpose to show clear when text is empty? What is the expected behavior in case of clicking on clear button ?

You can close this issue with by design.

**Comment by Toothpickliu** [comment]
> Clear button shows in case of user input text. What is the purpose to show clear when text is empty? What is the expected behavior in case of clicking on clear button ?

For this case, because is Edit function, the text box is not empty. Will display the address user already saved.So should be have the clear button. Please check the UX flow here:https://www.figma.com/file/khwN0kYvlm0y5i408dCXfy/Search-SDK?node-id=219%3A10154
<img width="289" alt="image" src="https://user-images.githubusercontent.com/102219534/159667483-79b73aea-42da-4474-9d27-67e8d9c28ff6.png">

**Comment by arambaghdasintellias** [comment]
Fixed.

**Comment by Joeyd321** [comment]
Verify in version 0.6, result is PASS.
